name: Mend Security Scan
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '.github/workflows/**'

  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ master, main ]

  workflow_dispatch:

jobs:
  Mend:
    name: Mend Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - name: Mend Action 
      uses: LexisNexis-RBA/risk-seceng-MendGitHubAction@a8c2b768e1c2c3505f015acc0622f0540c75de37
      with:
        WS_APIKEY: ${{ secrets.WS_APIKEY }}
        WS_USERKEY: ${{ secrets.WS_USERKEY }}
        WS_PRODUCTTOKEN: ${{ secrets.WS_PRODUCTTOKEN }}
        WS_PROJECTNAME: ${{ github.event.repository.name }}
        WS_SCANCOMMENT: ${{ github.ref_name }}
