name: TruffleHog
permissions:
  contents: read
  pull-requests: read
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 0
    - name: TruffleHog
      uses: LexisNexis-RBA/risk-seceng-SecretScanningGitHubAction@0dc63f0ef58a8bbc5117dcc7c7fadd6819999a71
